// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj_Ylf9dSzcwZfSAF7uf5WyKSdPU1Sg5A',
    appId: '1:919381510134:web:913531d97f21fc48c329d7',
    messagingSenderId: '919381510134',
    projectId: 'contact-hub-8be3f',
    authDomain: 'contact-hub-8be3f.firebaseapp.com',
    storageBucket: 'contact-hub-8be3f.appspot.com',
    measurementId: 'G-HVQX93PZH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrMT8WALuNh0RaCUkMEYU6xC9FzkAE_nc',
    appId: '1:919381510134:android:42dc6b8941c05e7ec329d7',
    messagingSenderId: '919381510134',
    projectId: 'contact-hub-8be3f',
    storageBucket: 'contact-hub-8be3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfptDVat2yu6oxKE6u7dwslMLrEeW_Fp8',
    appId: '1:919381510134:ios:6d694499f8c46e1ec329d7',
    messagingSenderId: '919381510134',
    projectId: 'contact-hub-8be3f',
    storageBucket: 'contact-hub-8be3f.appspot.com',
    iosBundleId: 'com.example.contactHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfptDVat2yu6oxKE6u7dwslMLrEeW_Fp8',
    appId: '1:919381510134:ios:6d694499f8c46e1ec329d7',
    messagingSenderId: '919381510134',
    projectId: 'contact-hub-8be3f',
    storageBucket: 'contact-hub-8be3f.appspot.com',
    iosBundleId: 'com.example.contactHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj_Ylf9dSzcwZfSAF7uf5WyKSdPU1Sg5A',
    appId: '1:919381510134:web:5fc9d184b41a00a4c329d7',
    messagingSenderId: '919381510134',
    projectId: 'contact-hub-8be3f',
    authDomain: 'contact-hub-8be3f.firebaseapp.com',
    storageBucket: 'contact-hub-8be3f.appspot.com',
    measurementId: 'G-TGMZ4ZFCFX',
  );
}
